name: "P6 GHA: Builds a CDK Construct"
description: "P6 GHA: Builds a CDK Construct"
author: "Philip M. Gollucci"
inputs:
  aws_region:
    description: "AWS region for deployment"
    required: false
    default: "us-east-1"
  aws_role:
    description: "AWS role to assume"
    required: false
  aws_session_name:
    description: "Session name for the AWS role"
    required: false
  cdk_deploy_account:
    description: "AWS CDK deploy account"
    required: false
  cdk_deploy_region:
    description: "AWS CDK deploy region"
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v6.0.1
    - name: Setup Node
      uses: p6m7g8-actions/node-yarn-setup@main
    - name: Assume role using OIDC
      uses: aws-actions/configure-aws-credentials@v5.1.1
      with:
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: ${{ inputs.aws_role }}
        role-session-name: ${{ inputs.aws_session_name }}
    - name: Run build
      shell: bash
      env:
        CDK_DEPLOY_ACCOUNT: ${{ inputs.cdk_deploy_account }}
        CDK_DEPLOY_REGION: ${{ inputs.cdk_deploy_region }}
        CDK_DEFAULT_ACCOUNT: ${{ inputs.cdk_deploy_account }}
        CDK_DEFAULT_REGION: ${{ inputs.cdk_deploy_region }}
        AWS_REGION: ${{ inputs.aws_region }}
      run: yarn run ci:gha
    - name: Run Package
      shell: bash
      run: yarn run jsii:pacmak:parallel
